# Cloudflare Workers 設定ファイル
# Workers Static Assets を使用して静的サイトを配信
# 参考: https://developers.cloudflare.com/workers/static-assets/

name = "porterm"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"
